title: "'(NÓR)"
author: Neal Ó Riain
email: neal.o.riain@gmail.com
description: Former astrophysicist, current Irishman abroad. Big fan of numbers.

# social links
twitter_username: neal_o_r
github_username:  neal-o-r

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
